### ISSUE TITLE
Main translation component listed as glossary

### ISSUE THREAD

**Issue by comradekingu** [dgsasha/remembrance#10]
https://hosted.weblate.org/projects/reminders/reminders/ should not be a glossary, as that makes it much harder to translate.

I think it can be changed in https://hosted.weblate.org/settings/reminders/reminders/ :)

You can add "kingu" in https://hosted.weblate.org/access/reminders/#users if you want,
and then I can look for other things to change.
Usually there are some things to get right before it is approved for the libre project plan. :)

**Comment by dgsasha** [comment]
Thanks for letting me know, just fixed this
