### ISSUE TITLE
Add support for syncing with CalDAV

### ISSUE THREAD

**Issue by xplosionmind** [dgsasha/remembrance#14]
Add the possibility of synchronizing with CalDAV

**Comment by dgsasha** [comment]
I will look into this, but it doesn't really seem necessary. This app is just meant to set reminders for things, it's not really a calendar app, and it doesn't follow the standards of typical calendar apps so it wouldn't sync all that well. I think syncing with Google tasks would make more sense, which is something I will consider adding.

**Comment by dgsasha** [comment]
Google Tasks doesn't support setting times when using it's API, but Microsoft To Do does. Once I learn how to use Microsoft's API I will probably add support for syncing with Microsoft to do. I think this would be a good feature so you can sync reminders from your phone to your desktop.

**Comment by dgsasha** [comment]
I probably won't have time to work on this anytime soon, if someone else wants to help with this, say something here and I can help you get started and will assist you with developing this feature. It's just going to be too much work to do myself.

**Comment by dgsasha** [comment]
Alright cloud syncing with MS To Do should be fully functional now, it will be available in version 2.0 soon. If anyone wants to test it just build the main branch.

**Comment by hynet-mel** [comment]
Though, the Microsoft To-Do option is a great addition on its own and many people can make use of it on it's own
I did spot some misconception about CalDAV as it is not only calendar synchronization, and more seen as a standard to synchronize tasks as well over.  Personally I store all my tasks and calendars in Nextcloud and keep the ones for work over in Google (as that is required there) but both use CalDAV to syncronize both over to my devices.

Which I believe was @xplosionmind 's initial suggestion.
Here is a link of services compatible (or partially compatible) with CalDAV by tasks.org: https://tasks.org/docs/caldav_intro.html

I've never really don't anything like this either but I'd maybe see if I can mess around to make a PR or think along. But my familiarity with making GTK apps is very limited though :(

**Comment by dgsasha** [comment]
> Though, the Microsoft To-Do option is a great addition on its own and many people can make use of it on it's own I did spot some misconception about CalDAV as it is not only calendar synchronization, and more seen as a standard to synchronize tasks as well over. Personally I store all my tasks and calendars in Nextcloud and keep the ones for work over in Google (as that is required there) but both use CalDAV to syncronize both over to my devices.
> 
> Which I believe was @xplosionmind 's initial suggestion. Here is a link of services compatible (or partially compatible) with CalDAV by tasks.org: https://tasks.org/docs/caldav_intro.html
> 
> I've never really don't anything like this either but I'd maybe see if I can mess around to make a PR or think along. But my familiarity with making GTK apps is very limited though :(

Yeah I was wrong about this. Reopening this issue.

**Comment by dgsasha** [comment]
I'll probably get started in about a week once I'm done with finals. Also, any help would be appreciated because I don't know much about CalDAV.

**Comment by dgsasha** [comment]
This feature will be available in v5.0 which will be released in the coming weeks. I've written all of the code for it but I havent really tested anything because I don't have any accounts that use CalDAV for tasks. Can anyone recommend a free service I can test this with?

**Comment by hynet-mel** [comment]
> I'll probably get started in about a week once I'm done with finals. Also, any help would be appreciated because I don't know much about CalDAV.
Take your time, I can try to look around for similar projects/code but I am not the best when it comes to actual programming.

> Can anyone recommend a free service I can test this with?
I see on tasks.org 's service section that https://fruux.com/ might be a good option, but I personally use my account over at disroot.org that has a lot of services. Just registering there takes a while due to manual screening.

**Comment by dgsasha** [comment]
> > I'll probably get started in about a week once I'm done with finals. Also, any help would be appreciated because I don't know much about CalDAV.
> 
> Take your time, I can try to look around for similar projects/code but I am not the best when it comes to actual programming.
> 
> > Can anyone recommend a free service I can test this with?
> 
> I see on tasks.org 's service section that https://fruux.com/ might be a good option, but I personally use my account over at disroot.org that has a lot of services. Just registering there takes a while due to manual screening.

Thanks! I tried out fruux and it works alright. Pretty happy with how easy all of this was tbh. Most of the work I did on Microsoft To Do support was really easy to translate over to CalDAV. I'm also thinking about adding support for importing and exporting lists through .ical files but this might be delayed until after 5.0

**Comment by dgsasha** [comment]
v5.0 with CalDAV support is headed to Flathub Beta right now. Once its up can some people please test it and provide some feedback here? Everything seems to work for me, including recurring reminders, but it doesn't support everything in the CalDAV spec so there could be issues with some servers.

**Comment by dgsasha** [comment]
> > v5.0 with CalDAV support is headed to Flathub Beta right now. Once its up can some people please test it and provide some feedback here? Everything seems to work for me, including recurring reminders, but it doesn't support everything in the CalDAV spec so there could be issues with some servers.
> 
> It works! However, it doesn't seem that the date is synced. I.e., if you create a task on a CalDAV server with https://tasks.org, and set the date for like "tomorrow", no date shows in Remembrance, and the task is sorted in alphabetical order.

The date should be synced through the DUE property. Maybe the server is setting the DTSTART property only. Can you access the data somehow, like downloading an icalendar file from the server? Then from there you could check what properties are being set on the VTODO components.

**Comment by dgsasha** [comment]
Actually ignore that, it looks like I messed something up

**Comment by julianfairfax** [comment]
> Actually ignore that, it looks like I messed something up
> 
> Edit: This is fixed in [75948b7](https://github.com/dgsasha/remembrance/commit/75948b704cf5fded55e2a57e18b2916e5808852e)

Yay! I'll update when it's on Flathub

**Comment by AbrarSL** [comment]
Can this be used to sync with Google Tasks? I tried to connect to a Google account but it won't seem to work?

EDIT: It looks like it might not be able to, https://developers.google.com/calendar/caldav/v2/guide#connecting_to_googles_caldav_server

**Comment by dgsasha** [comment]
> Can this be used to sync with Google Tasks? I tried to connect to a Google account but it won't seem to work?
> 
> EDIT: It looks like it might not be able to, https://developers.google.com/calendar/caldav/v2/guide#connecting_to_googles_caldav_server

I don't think so, and I'm personally not going to be adding support for googles API due to all of the limitations that come with it. I messed around with it for a bit and it doesn't support syncing recurring tasks or reminders through the API, which would make adding support to this app pretty much pointless. I know some people probably like google tasks, and if anyone wants to make a pull request that adds support I would happily merge it, but it just seems like too much work for something that has barely any features. Endeavour already supports google tasks so if anyone wants to sync with google tasks they should probably just use that.
