### ISSUE TITLE
[BUG] Tasks disappear when updating Fedora

### ISSUE THREAD

**Issue by Scotty-Trees** [dgsasha/remembrance#18]
Using the flatpak Remembrance (Reminder?) v1.1 on Fedora 37. No issues when I run `flatpak update` or `dnf update` on Fedora. However, when I have reminders saved in your application and I happen to run the update command `sudo dnf update --refresh` (essentially forces an immediate update of the repository lists), all the reminders disappear/get erased. No idea how or why this happens. I've tested this numerous times and have come to the same conclusion. I checked Gnome Logs for an indication and it looks like some backend service reminder is failing, here's a screenshot of a few of the logs errors I could find, hopefully it's helpful. 

![Screenshot from 2023-03-08 19-50-01](https://user-images.githubusercontent.com/45135187/223886646-30b860ea-fb90-4812-adce-3092ee915b28.png)

**Comment by dgsasha** [comment]
Can you post the contents of `~/.var/app/io.github.dgsasha.Remembrance/data/remembrance/reminders.csv`? If theres any personal info in there just remove it from your post, i just want to see if the file is corrupt

**Comment by Scotty-Trees** [comment]
```
/home/scott/.var/app/io.github.dgsasha.Remembrance/data/remembrance/reminders.csv  
JXeaPBMT,Cut Tom's nails,,1678323600,False,0,1,4,0,1,0
5ouGuD3T,Cut tom's nails,,1678323600,False,0,1,4,0,1,0
C44meDw3,test,test,1678325940,False,0,1,4,0,1,0
NWQz42EC,new,new,1678333140,False,0,1,4,0,1,0
MSwdGVHU,TEST,hi,0,False,0,1,4,0,1,0
j0Y0vukN,BYE,later,0,False,0,1,4,0,1,0
nzAcY1Gu,CUT nails,hygenie,1678333320,False,0,1,4,0,1,0
IyNaNKjI,test,test,0,False,0,1,4,0,1,0
byMc00Dp,new,new,1678329780,False,0,1,4,0,1,0
```

Let me know if you need anything else.

**Comment by dgsasha** [comment]
I cant reproduce this on my fedora system. I'll look at it again tomorrow but my guess is the app crashed and it corrupted the data file somehow, but I really dont know why that would happen. There is definitely something in the file though, or else it wouldnt show that error message, so hopefully they arent actually lost. Theres also a crash reported in the log that is visible in the screenshot, was that just you killing the service? If not can you send a screenshot of the full message (you can click on it to show more info)

**Comment by Scotty-Trees** [comment]
```
 7:58:02 PM gnome-keyring-d: asked to register item /org/freedesktop/secrets/collection/login/7, but it's already registered
 7:53:51 PM systemd: dbus-:1.2-org.gnome.Logs@0.service: Consumed 2.757s CPU time.
 7:53:51 PM gnome-logs: invalid unclassed pointer in cast to 'GtkListBoxRow'
 7:51:56 PM cat: Fontconfig error: Cannot load default config file: No such file: (null)
 7:50:03 PM systemd: Started tracker-extract-3.service - Tracker metadata extractor.
 7:49:53 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:49:52 PM systemd: Started dbus-:1.2-org.gnome.Screenshot@1.service.
 7:48:30 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:48:29 PM systemd: Started dbus-:1.2-org.gnome.Logs@0.service.
 7:48:24 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:48:22 PM systemd: Started app-flatpak-io.github.realmazharhussain.GdmSettings-56055.scope.
 7:47:31 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:47:31 PM remembrance: 2023-03-08 19:47:31,806 - Reminders - INFO - application:connect_to_service - Connected to service
 7:47:31 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55900.scope.
 7:47:25 PM gnome-shell: g_closure_unref: assertion 'closure->ref_count > 0' failed
 7:45:27 PM remembrance: 2023-03-08 19:45:27,774 - Reminders - INFO - application:connect_to_service - Connected to service
 7:45:27 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55718.scope.
 7:44:33 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:44:32 PM remembrance: 2023-03-08 19:44:32,900 - Reminders - INFO - application:connect_to_service - Connected to service
 7:44:32 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55562.scope.
 7:44:30 PM sudo: pam_unix(sudo:session): session closed for user root
 7:44:25 PM systemd: dbus-:1.2-io.github.dgsasha.Remembrance.Service1@4.service: Failed with result 'exit-code'.
 7:44:23 PM sudo: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
 7:44:18 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:44:18 PM remembrance: 2023-03-08 19:44:18,362 - Reminders - INFO - application:connect_to_service - Connected to service
 7:44:18 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55464.scope.
 7:44:12 PM sudo: pam_unix(sudo:session): session closed for user root
 7:44:00 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:44:00 PM remembrance: 2023-03-08 19:44:00,165 - Reminders - INFO - application:connect_to_service - Connected to service
 7:43:59 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55395.scope.
 7:43:39 PM gnome-shell: g_closure_unref: assertion 'closure->ref_count > 0' failed
 7:43:26 PM cat: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
 7:43:25 PM gnome-keyring-d: asked to register item /org/freedesktop/secrets/collection/login/5, but it's already registered
 7:43:04 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:43:04 PM remembrance: 2023-03-08 19:43:04,671 - Reminders - INFO - application:connect_to_service - Connected to service
 7:43:04 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-55125.scope.
 7:42:56 PM sudo: pam_unix(sudo:session): session closed for user root
 7:42:55 PM systemd: dbus-:1.2-io.github.dgsasha.Remembrance.Service1@3.service: Failed with result 'exit-code'.
 7:42:50 PM sudo: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
 7:42:44 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:42:44 PM remembrance: 2023-03-08 19:42:44,721 - Reminders - INFO - application:connect_to_service - Connected to service
 7:42:44 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-54753.scope.
 7:42:05 PM gnome-shell: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
 7:42:05 PM remembrance: 2023-03-08 19:42:05,044 - Reminders - INFO - application:connect_to_service - Connected to service
 7:42:04 PM systemd: Started app-flatpak-io.github.dgsasha.Remembrance-54679.scope.
```
I just opened the Logs in a text document and copied over the one that seemed related just to Remembrance. I appreciate you taking the time to have a look btw. No worries if you can't figure it out right away, these things can be a little tricky sometimes. Let me know if the above info was what you were asking for.

**Comment by dgsasha** [comment]
> ```
> /home/scott/.var/app/io.github.dgsasha.Remembrance/data/remembrance/reminders.csv  
> JXeaPBMT,Cut Tom's nails,,1678323600,False,0,1,4,0,1,0
> 5ouGuD3T,Cut tom's nails,,1678323600,False,0,1,4,0,1,0
> C44meDw3,test,test,1678325940,False,0,1,4,0,1,0
> NWQz42EC,new,new,1678333140,False,0,1,4,0,1,0
> MSwdGVHU,TEST,hi,0,False,0,1,4,0,1,0
> j0Y0vukN,BYE,later,0,False,0,1,4,0,1,0
> nzAcY1Gu,CUT nails,hygenie,1678333320,False,0,1,4,0,1,0
> IyNaNKjI,test,test,0,False,0,1,4,0,1,0
> byMc00Dp,new,new,1678329780,False,0,1,4,0,1,0
> ```
> 
> Let me know if you need anything else.

I didnt see this reply earlier, I'm on my phone right now and GitHub doesn't refresh automatically on mobile I guess. Anyways, it just looks like the header is missing (assuming this is the whole file). Try copying this file somewhere else, and then delete the file from the `remembrance` directory.  then open the app, create a new reminder, and it should regenerate the file with the header. Then close the app , and add the contents of the old file to the new file that was created (make sure you keep the header intact). then run `flatpak run io.github.dgsasha.Remembrance --restart-service` and your reminders should be there.

**Comment by Scotty-Trees** [comment]
Sorry, missed your last message, but just got the v1.3 update and tested this out again and it looks to be fixed! Thanks again for making a very useful application and hope to see it get better and better in the future. Thanks!
