### ISSUE TITLE
[Request]: Show lists in the sidebar, rather than requiring an extra click

### ISSUE THREAD

**Issue by zachbr** [dgsasha/remembrance#28]
### Tell us the problem or your need

I often use lists to separate tasks according to a category or type. Accessing lists in Remembrance (Reminders? - which name is preferred?) takes an extra click to open the "All Lists" menu even when there's plenty of room in the sidebar for those lists to appear. It'd be nice if this could be simplified so the extra click wasn't required.

Microsoft's To Do app on macOS (similar on Windows):
<img width="234" alt="Screenshot 2023-04-16 at 3 05 51 PM" src="https://user-images.githubusercontent.com/1254957/232339710-5a3e49b1-5baa-43e5-a62c-d6e1cfc4c835.png">

Remembrance:
<img width="262" alt="Screenshot 2023-04-16 at 3 13 14 PM" src="https://user-images.githubusercontent.com/1254957/232339716-857bf773-27e9-436f-aacb-cc4cd9c6a182.png"> <img width="226" alt="Screenshot 2023-04-16 at 3 13 39 PM" src="https://user-images.githubusercontent.com/1254957/232339719-6876a1d0-7b40-4c40-9e1b-c67806cbe40d.png">

### Describe the solution you'd like

I would love to see the lists just be visible in the sidebar all the time - except perhaps when the window is too small to show them (but maybe it could be scrollable?)

### Additional context

I spend a lot of time jumping between operating systems and frequently use Microsoft's To Do app, so I may be just a bit biased towards something closer to that UI. On that topic, thank you for making the app. It is nice to find a native solution for Linux :)

**Comment by dgsasha** [comment]
Honestly now that you mention it I'm not really sure why I chose this design. Maybe it's a little neater but it's also sort of awkward. I'll look into this tomorrow, and will also consider adding a button to open the edit lists window on the sidebar as well.

**Comment by dgsasha** [comment]
This is coming in the next update (3.8, probably releasing tomorrow). I've also updated the screenshots [here](https://github.com/dgsasha/remembrance/blob/main/README.md) if you want to see what it looks like.
