### ISSUE TITLE
[Bug]: No notification if the app is closed

### ISSUE THREAD

**Issue by hyuri** [dgsasha/remembrance#33]
### Package

Flathub

### Distribution

Pop!_OS 22.04

### Describe the bug

After setting reminders, I get no notifications if the app is closed.

I expected my reminders to alert me even if the app was closed.

### To Reproduce

1. Open the app
2. Set a reminder to ring at a specific time
3. Close the app
4. Wait until the time of the reminder and notice how you don't get the notification

### Additional context

Other reminder and timer apps I've used notify me even when the app is closed.

**Comment by dgsasha** [comment]
Does the app have permission to run in the background? You should be able to check this in flatseal. I'll try to see if i can reproduce this tomorrow but this shouldn't be happening if the app is allowed to run in the background.

**Comment by hyuri** [comment]
> Does the app have permission to run in the background? You should be able to check this in Flatseal.

It didn't. Not sure why. I just gave it permission and tried again: now it works!

Thanks!
