### ISSUE TITLE
[Request]: Follow GNOME HIG in App Icon

### ISSUE THREAD

**Issue by TheKrafter** [dgsasha/remembrance#42]
### Tell us the problem or your need

The App Icon does not fit gnome styling or human interface guidelines. The box around the bell is flat and unnecessary, and the bell is flat and longer than it should be, as the hig specifies:
> Avoid extreme aspect ratios for the icon shape, such as very narrow or very wide shapes.

### Describe the solution you'd like

Follow the GNOME [Human Interface Guidelines for App Icons](https://developer.gnome.org/hig/guidelines/app-icons.html)

**Comment by TheKrafter** [comment]
Tobias has a great blog post on app icons, the first portion neatly outlines _why_ this is important: https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app/

**Comment by dgsasha** [comment]
Yeah this app needs a new icon. I'm not an artist so if someone else wants to contribute it would be very much appreciated. Windows support for the app is almost ready (albeit experimental, there are still some issues), and since the app is going to be on the Microsoft store and will be published in a much larger ecosystem it also needs a new name. I've decided on the name 'Mnemonic', maybe it could be incorporated into the new icon somehow and the bell could be dropped, as this app is more than just a simple reminder app now.

**Comment by dgsasha** [comment]
If nobody contributes anything I'll try to update it myself, but I'll wait a bit and see if anybody else wants to help first.

**Comment by TheKrafter** [comment]
I do think reminders or "Remembrance" (as its referred to here and there iirc) is good, and I'm not entirely certain that "Mnemonic" fits the [HIG for app names](https://developer.gnome.org/hig/guidelines/app-naming.html).

And if you want my two cents about publishing to the windows platform / microsoft store: don't prioritize it when this is clearly a linux-first app.

**Comment by edfloreshz** [comment]
I'm not much of an artist either but I tried to make the icon a little bit better

![image](https://github.com/remindersdevs/Reminders/assets/22224438/fb28a117-7817-438c-aaa1-8e7b0964a3a0)

We could perhaps tweak the bell and make it look better, although, @dgsasha thinks the bell should be abandoned altogether.

I think it looks good in conjunction with other GNOME icons, what do you all think?

**Comment by TheKrafter** [comment]
I do think the bell is a good idea, because (at least for me) this reminders app works well for sending me notifications about things i need to get done-- which makes a bell make a lot of sense.

I think @edfloreshz removal of the square background makes it look MUCH better and fit much better with other GNOME app icons, but the bell still has a few problems:
- the proportions are to narrow [(see hig)](https://developer.gnome.org/hig/guidelines/app-icons.html#size-shape)
- the bottom portion and top nub of the bell uses too small of detail units [(see hig)](https://developer.gnome.org/hig/guidelines/app-icons.html#perspective)
- the main portion of the bell is too flat [(see hig)](https://developer.gnome.org/hig/guidelines/app-icons.html#material-lighting)

**Comment by dgsasha** [comment]
Okay so I think I've decided on a better name for the app. 'Cue'. It fits the GNOME HIG but is still fairly unique and describes the app well enough. I'll start tinkering with the icon some tonight, the background should definitely be removed, maybe the bell should stay though, because there aren't many other alternatives.

**Comment by dgsasha** [comment]
I think @TheKrafter has some good points. I'll have some ideas for making it better so I'll see what I can do.

**Comment by bragefuglseth** [comment]
Feel free to reach out to the [GNOME App Icon Design group](https://matrix.to/#/#appicondesign:gnome.org) on Matrix! We can provide support and feedback.

**Comment by dgsasha** [comment]
![App Icon](https://github.com/remindersdevs/Reminders/assets/86973360/98079574-79ae-4a15-a78b-6f8a6e5c6d9b)
How's this @TheKrafter? I think it fixes all of the things you mentioned.

**Comment by dgsasha** [comment]
![App Icon](https://github.com/remindersdevs/Reminders/assets/86973360/59006686-c31e-4692-ab58-32514e3bcbd7)
Here's a higher res render

Edit: updated with improved colors

**Comment by dgsasha** [comment]
It probably could use more contrast but I think it looks a lot better
